version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/tests/harness"
    schedule:
      interval: "weekly"
    groups:
      synchronized-dependencies:
        group-by: "dependency-name"
